language: go
go:
  - 1.8
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get ./...
script:
  # test based on datastore
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - export CLOUDSDK_CORE_PROJECT=weaviate-dev-001
  - export DATASTORE_DATASET=weaviate-dev-001
  - export DATASTORE_EMULATOR_HOST=127.0.0.1:8081
  - export DATASTORE_EMULATOR_HOST_PATH=127.0.0.1:8081/datastore
  - export DATASTORE_HOST=http://127.0.0.1:8081
  - export DATASTORE_PROJECT_ID=weaviate-dev-001
  - export DATASTORE_EMULATOR_HOST=localhost:8081
  - nohup gcloud beta emulators datastore start --no-store-on-disk &
  - sleep 60
  - rm nohup.out
  - nohup go run ./cmd/weaviate-server/main.go --scheme=http --port=8080 --host=127.0.0.1 &
  - sleep 12
  - export WEAVIATEKEY=$(grep "ROOTKEY=" nohup.out | cut -d "=" -f 2)
  - go test -v ./test -args -api-key=$WEAVIATEKEY
  - rm nohup.out
  # compile and commit update
  - mkdir src/
  - env CGO_ENABLED=0 GOOS=darwin GOARCH=386 go build -o ./src/weaviate_darwin_386 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./src/weaviate_darwin_amd64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=darwin GOARCH=arm go build -o ./src/weaviate_darwin_arm ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ./src/weaviate_darwin_arm64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=freebsd GOARCH=386 go build -o ./src/weaviate_freebsd_386 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o ./src/weaviate_freebsd_amd64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=freebsd GOARCH=arm go build -o ./src/weaviate_freebsd_arm ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o ./src/weaviate_linux_386 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./src/weaviate_linux_amd64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o ./src/weaviate_linux_arm ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o ./src/weaviate_linux_arm64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=ppc64 go build -o ./src/weaviate_linux_ppc64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -o ./src/weaviate_linux_ppc64le ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=mips go build -o ./src/weaviate_linux_mips ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -o ./src/weaviate_linux_mipsle ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=mips64 go build -o ./src/weaviate_linux_mips64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=linux GOARCH=mips64le go build -o ./src/weaviate_linux_mips64le ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=netbsd GOARCH=386 go build -o ./src/weaviate_netbsd_386 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -o ./src/weaviate_netbsd_amd64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=netbsd GOARCH=arm go build -o ./src/weaviate_netbsd_arm ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=openbsd GOARCH=386 go build -o ./src/weaviate_openbsd_386 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -o ./src/weaviate_openbsd_amd64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=openbsd GOARCH=arm go build -o ./src/weaviate_openbsd_arm ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=plan9 GOARCH=386 go build -o ./src/weaviate_plan9_386 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=plan9 GOARCH=amd64 go build -o ./src/weaviate_plan9_amd64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=solaris GOARCH=amd64 go build -o ./src/weaviate_solaris_amd64 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o ./src/weaviate_windows_386 ./cmd/weaviate-server/main.go
  - env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./src/weaviate_windows_amd64 ./cmd/weaviate-server/main.go